name: swag-labs-tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-jammy

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
        env:
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          LOCKED_USER: ${{ secrets.LOCKED_USER }}
          PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
          PERFORMANCE_USER: ${{ secrets.PERFORMANCE_USER }}
          ERROR_USER: ${{ secrets.ERROR_USER }}
          VISUAL_USER: ${{ secrets.VISUAL_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
