name: Playwright

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx playwright test
